title: Toucanix Site
description: "The offical site for toucanix (Operating System)"
remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

theme_mode: auto   # auto | dark | light
